### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by hopewise** [matehat/cqex#3]
Hello,

I have just installed Cassandra via docker, and installed cqex, but I can't see any docs about where to set the config ? like host, port, database name, user name, password?

**Comment by cjbottaro** [comment]
Same problem here.  I get that `CQEx.Client.new!` just delegates to `cqerl`, so that you can connect to a cluster via a single node like:

``` elixir
client = CQEx.Client.new! {"127.0.0.1", 9042}
```

But what about
https://github.com/matehat/cqerl/#using-environment-variables

Or
https://github.com/matehat/cqerl/#clusters

How does a `sys.config` or `app.config` in Erlang map to `Mix.Config` in Elixir?  I'm guessing that we're _supposed_ to be able to say stuff like:

``` elixir
use Mix.Config

config :cqex, :cluster1, nodes: [{10.0.0.1, 9042}, {10.0.0.1, 9042}]

config :cqex, :cluster2, nodes: [{10.0.1.1, 9042}, {10.0.1.1, 9042}]
```

Then be able to say:

``` elixir
client = CQEx.Client.get(:cluster1)
do_query_with(client, "...") # Something like this.
```

How to do this?

**Comment by hopewise** [comment]
Any update on this issue?

**Comment by matehat** [comment]
Sorry for the unavailability of support for how to get started

So, the way to set it up and use it is pretty much like how @cjbottaro suggested, except that you configure the nodes as `config :cqerl` not `config :cqex`.

If you want different clusters:

``` elixir
# In your project's config/config.exs
use Mix.Config

config :cqerl, 
  cassandra_clusters: [
    cluster1: { ["10.0.0.1:9042", "10.0.0.2:9042"], [keyspace: "keyspace1"] },
    cluster2: { ["10.0.0.1:9042", "10.0.0.2:9042"], [keyspace: "keyspace2"] }
  ]

# Then, in your code

client = CQEx.Client.new! :cluster1
# etc
```

And if you're using a single cluster:

``` elixir
# In your project's config/config.exs
use Mix.Config

config :cqerl, 
  cassandra_nodes: [ "10.0.0.1:9042", "10.0.0.1:9042" ],
  keyspace: "keyspace"

# Then, in your code

client = CQEx.Client.new!
# etc
```
